### ISSUE TITLE
lack of word embedding files

### ISSUE THREAD

**Issue by TrafalgarRicardoLu** [Atmegal/On-Exploring-Indeterminate-Relationships-for-Visual-Relationship-Detection#2]
I try to run this project but I notice that _oList_word_embedding.npz_, _oList_word_embedding.npz_ and _inter.npz_ are not found. Are they result of certain nets or can be downloaded instantly?

**Comment by Atmegal** [comment]
I have uploaded these files in input/VRD. The codes for generating these files can be found in process. Since the Glove dataset is too big, you can download them in https://nlp.stanford.edu/projects/glove/. Thank you so much.

**Comment by TrafalgarRicardoLu** [comment]
Sorry to bother you again, but I can't find pretained model which has same name with yours. Do you use your own pretrained model? If not, I would appreciate it if you could give me the download link.

**Comment by Atmegal** [comment]
Some files are too big to be uploaded. We will upload them in the future, maybe using google driver. You can download some files in https://github.com/yangxuntu/vrd. The faster R-CNN ckpt can be used in our code.  Note that their models are trained on the whole training dataset, which is different from our model trained on part of the training dataset. We are still fixing our code. Thank you for your question.

**Comment by TrafalgarRicardoLu** [comment]
I find that there is lack of a package named **inter.npz**, which is under **fuse_res**, when I try to train relation network. I think it's important file to this project, hope to hear from you about how to get it.
